### ISSUE TITLE
Example learning with STDP

### ISSUE THREAD

**Issue by vankhoa21991** [CEA-LIST/N2D2#34] opened 2019-07-15 16:27 UTC
Hello, do you have any example .ini that create a SNN and train with STDP? Thank you

**Comment by olivierbichler-cea** [comment] 2019-07-22 08:54
Hello,
I just added an example reproducing our IJCNN 2011 paper: models/mnist-stdp-ijcnn.ini
Please check the latest commit: eedfafb20fa9dc369786d7663a30cc1187fd0f8c
Olivier

**Comment by vankhoa21991** [comment] 2019-07-24 08:16
Thanks i'm testing it, but it hasn't stop training for 2 days already, and the success rate is about 72%

**Comment by olivierbichler-cea** [comment] 2019-07-26 07:58
This is the correct behavior, 70-74% is the expected score range. Actually the simulation reaches this accuracy well before it ends, so you can stop it as soon as you reach this score, the state will be saved.

**Comment by olivierbichler-cea** [comment] 2019-09-06 13:14
No further activity, the issue is considered solved. Closing.

**Closed by olivierbichler-cea** 2019-09-06 13:14 UTC
Labels: question
