### ISSUE TITLE
Example model `mnist24_16c4s2_24c5s2_150_10_Spike.ini` is broken

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#61] opened 2020-01-17 06:30 UTC
Hi,

I am trying to do ,

```
_prachi@prachi-V530-15ICB:~/N2D2/build/bin$ ./n2d2 /home/prachi/N2D2/models/mnist24_16c4s2_24c5s2_150_10_Spike.ini -learn 6000000 -log 10000_


After the training is done it is showing me this error,
_'Error: Tensor<T>::load(): mismatch in tensor size!'_
 
With this if I go ahead for testing , I encounter this error: 
_'Error: Could not open synaptic file: weights_range_normalized/conv1_weights.syntxt'_

As it does not support nonintegral export for now , I am exporting it with calibration option. So at the end I get this error:
_'Error: Could not open synaptic file: weights_range_normalized/conv1_weights.syntxt
prachi@prachi-V530-15ICB:~/N2D2/build/bin$ '_
```

Can anyone please tell me why is it giving these errors?

**Comment by cmoineau** [comment] 2022-03-03 10:35
Duplicate of #70 closing this issue

**Closed by cmoineau** 2022-03-03 10:35 UTC
